spring:
  batch:
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: local
    include: google, naver, kakao
  datasource:
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&serverTimeZone=asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  messages:
    basename: errors
  mail:
    host: smtp.gmail.com
    port: 587
    username: kyoungsuk3254@gmail.com
    password: cnlgfpagxudlgjzl
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: govlepel@$&

google:
  recaptcha:
    key:
      site: 6LdZr7IhAAAAAMyl6j8SePtlJ2K1TsQRLpXtXU1J
      secret: 6LdZr7IhAAAAANAq_R-Lo7vdx5H3fhS6KngcQ5wu
      url: https://www.google.com/recaptcha/api/siteverify

logging:
  level:
    org.hibernate.SQL: debug
